stages:
 - heroku_deploy_staging

heroku_deploy_staging:
 stage: heroku_deploy_staging
 only:
 - staging
 script:
 - cd backend/
 - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/virgil-dev.git
 - git push -f heroku master